# ╔══════════════════════════════════════════════╗
# ║              HYPRLAND CONFIG                 ║
# ╚══════════════════════════════════════════════╝

monitor=,1920x1080@200,auto,1

# AUTOSTART
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar
exec-once = swww-daemon
exec-once = hyprctl setcursor Bibata-Modern-Ice 24

# PROGRAMS
$terminal = kitty
$fileManager = nautilus
$menu = fuzzel
$browser = firefox

# ENV
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# INPUT (teclado inglés 🔥)
input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }

    sensitivity = 0.5
}

# GENERAL
general {
    gaps_in = 6
    gaps_out = 18
    border_size = 2

    col.active_border = rgba(33ccffee)
    col.inactive_border = rgba(444444aa)

    layout = dwindle
}

# DECORATION
decoration {
    rounding = 8

    blur {
        enabled = false
    }

    shadow{
      enabled = false 
      range = 30 
      render_power = 6
    }
}

# ANIMATIONS (más suaves)
animations {
    enabled = yes

    bezier = smooth, 0.25, 0.9, 0.1, 1.0

    animation = windows, 1, 6, smooth
    animation = fade, 1, 5, smooth
    animation = workspaces, 1, 5, smooth
}

# LAYOUT
dwindle {
    pseudotile = yes
    preserve_split = yes
}


# MISC
misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
}

# WINDOW RULES
windowrulev = float, class:(waypaper)
windowrulev = float, class:^(float_kitty)$
windowrulev = size 1200 700, class:^(float_kitty)$
windowrulev = opacity 0.95 0.95, class:^(Code)$

# MOD KEY
$mainMod = SUPER

# BINDS

# Apps
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod SHIFT, RETURN, exec, $terminal --class float_kitty
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, B, exec, $browser
bind = $mainMod, D, exec, $menu

# Window control
bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen
bind = $mainMod, V, togglefloating
bind = $mainMod, P, pseudo

# Focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Volume
binde = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-

# Brightness
bindel = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# Screenshot
bind = , PRINT, exec, hyprshot -m output --clipboard-only

# Mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
